version: '3.1'
services:
  db:
    image: mysql
    container_name: spring21-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - spring21_data:/var/lib/mysql

volumes:
  spring21_data: