server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spaceship?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace

management:
  endpoints:
    web:
      exposure:
#        include: "*"
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2021
  version: 1.0.0